# Generated by Django 5.1.3 on 2024-11-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('direccion_entrega', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='articulo',
        ),
        migrations.DeleteModel(
            name='rubro',
        ),
    ]
